import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import * as styles from "../../styles/Home.module.css"
import Layout from "../components/layout"

const IndexPage: React.FC<PageProps> = () => {
  return (
    <Layout>
      <div>
        <title>C_BP One</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          GraphQL API Callng Next.js App
        </h1>

        <p className={styles.description}>
          Testing Environment for Bleeding Edge
          <code className={styles.code}>code</code>
        </p>

        <figure className="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700">
          <a href="/characters?page=1" className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
            <div>
              <div>Connect Metamask &rarr;</div>
              <div>Authenticate with Metamask to see special page</div>
            </div>
          </a>
        </figure>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>
    </Layout>
  )
}

export default IndexPage

export const Head: HeadFC = () => <title>Home Page</title>
